name: Coverage
on:
  pull_request:
    branches:
      - master
jobs:
  coverage:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Report
      - uses: artiomtr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 60
